# Generated by Django 4.2.6 on 2024-06-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_candidate_job_vacancy_and_more"),
        ("vacancies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="competention",
            field=models.ManyToManyField(
                blank=True, related_name="vacancies", to="users.competention"
            ),
        ),
    ]
