# Generated by Django 4.2.6 on 2024-05-31 07:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="Имя пользователя",
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.CreateModel(
            name="CareerPoint",
            fields=[
                (
                    "career_point_id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("beginning_of_work", models.DateTimeField()),
                ("ending_of_work", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="CompanyInfo",
            fields=[
                (
                    "company_info_id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("company_name", models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name="Competention",
            fields=[
                (
                    "competention_id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("competention_name", models.CharField(max_length=125)),
                ("competention_experience", models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name="Responsibilities",
            fields=[
                (
                    "responsibilities_id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("about_responsibilities", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "role_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "role_name",
                    models.CharField(
                        max_length=125,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(5)],
                        verbose_name="Имя роли",
                    ),
                ),
                (
                    "about_role",
                    models.CharField(max_length=125, verbose_name="Кратко о роли"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobVacancy",
            fields=[
                (
                    "job_vacancy_id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("job_text", models.TextField()),
                ("job_title", models.CharField(max_length=55)),
                (
                    "competention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.competention",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompetentionProfile",
            fields=[
                (
                    "competention_profile_id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("scorepoint_hard_skill", models.IntegerField(default=0)),
                ("scorepoint_soft_skill", models.IntegerField(default=0)),
                ("scorepoint_job_vacancy", models.IntegerField(default=0)),
                (
                    "competention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.competention",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CareerProfile",
            fields=[
                (
                    "career_profile_id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("experience", models.IntegerField()),
                ("scorepoint_job_vacancy", models.IntegerField()),
                (
                    "career_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.careerpoint",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="careerpoint",
            name="company_info",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.companyinfo"
            ),
        ),
        migrations.AddField(
            model_name="careerpoint",
            name="responsibilities",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.responsibilities"
            ),
        ),
        migrations.AddField(
            model_name="careerpoint",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.role"
            ),
        ),
    ]
