# Generated by Django 4.2.6 on 2024-06-01 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0001_initial"),
        ("users", "0003_candidate_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="phone_number",
            field=models.CharField(default="Не указано", max_length=125),
        ),
        migrations.AddField(
            model_name="candidate",
            name="vacancy",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vacancies",
                to="vacancies.vacancy",
            ),
        ),
    ]
